export { default as IconArrowBack } from './arrow-back.svg'
export { default as IconEmail } from './email.svg'
export { default as IconGoogle } from './google.svg'
export { default as IconFacebook } from './facebook.svg'
export { default as IconEyeOpen } from './eye-open.svg'
export { default as IconEyeClosed } from './eye-closed.svg'
export { default as IconIdentity } from './identity.svg'
export { default as IconPassword } from './password.svg'
export { default as IconCheckSuccess } from './check-success.svg'
export { default as IconCheckError } from './check-error.svg'
export { default as IconChevronRight } from './chevron-right.svg'
export { default as IconLike } from './favorite.svg'
export { default as IconLiked } from './favorite-full.svg'

// -> Custom Tabbar
export { default as IconHome } from './custom-tab-bar/home.svg'
export { default as IconSearch } from './custom-tab-bar/search.svg'
export { default as IconToday } from './custom-tab-bar/today.svg'
export { default as IconFavorite } from './custom-tab-bar/favorite.svg'
export { default as IconAccount } from './custom-tab-bar/account.svg'

// -> Header
export { default as IconSearchLocation } from './header/search-location.svg'
export { default as IconNotification } from './header/notification.svg'

export type IconsTypes =
  | 'IconHome'
  | 'IconSearch'
  | 'IconToday'
  | 'IconFavorite'
  | 'IconToday'
  | 'IconAccount'
  | 'IconArrowBack'
  | 'IconEmail'
  | 'IconGoogle'
  | 'IconFacebook'
  | 'IconEyeOpen'
  | 'IconEyeClosed'
  | 'IconCheckSuccess'
  | 'IconCheckError'
  | 'IconChevronRight'
  | 'IconNotification'
  | 'IconSearchLocation'
  | 'IconLike'
  | 'IconLiked'
